channels:
- conda-forge
dependencies:
- python=3.11.0
- pip<=25.3
- pip:
  - mlflow==2.14.1
  - numpy==1.26.4
  - pandas==2.1.4
  - psutil==7.0.0
  - scikit-learn==1.5.2
  - scipy==1.16.1
  - xgboost==3.0.3
name: mlflow-env
